services:
  bot:
    build: .
    env_file:
      - .env
    environment:
      - OLLAMA_URL=http://host.docker.internal:11435
    networks:
      - plexllm_app-network
    volumes:
      - ./data:/app/data

networks:
  plexllm_app-network:
    external: true
