services:
  bot:
    build: .
    env_file:
      - .env
    environment:
      - OLLAMA_URL=http://plexllm-ollama-1:11434
    networks:
      - plexllm_app-network
    volumes:
      - ./data:/app/data

networks:
  plexllm_app-network:
    external: true
