version: '3.8'
services:
  bot:
    build: .
    env_file:
      - .env
    environment:
      - OLLAMA_URL=http://ollama:11434
    networks:
      - plexllm_app-network

networks:
  plexllm_app-network:
    external: true
